/**
 * Short re-exports of generated Wails v3 bindings so Vue components do not
 * depend on the long module path under frontend/bindings/.
 */
export {
  CreateCategory,
  CreateSource,
  DailyContent,
  DailyIndex,
  DeleteCategory,
  DeleteSource,
  HomeDir,
  ListArticles,
  ListCategories,
  ListSources,
  PreviewSource,
  ReadConfig,
  ReadSecrets,
  RebuildHistoryIndex,
  RestartToUpdate,
  SaveAgentAPIKey,
  SaveAgentConfig,
  SaveConfig,
  SaveSchedule,
  SaveWebhook,
  SetSourceEnabled,
  StartupError,
  SupportedAgentProviders,
  SupportedParseTypes,
  TriggerNow,
  UpdateCategory,
  UpdateSource,
  UpdateState,
  Version,
} from '../bindings/github.com/vogo/informer/cmd/informer-ui/app'

export type {
  AgentConfigDTO,
  ArticleDTO,
  ArticleItemDTO,
  ArticlePageDTO,
  ArticleQueryRequest,
  CategoryDTO,
  ConfigViewDTO,
  DailyDayDTO,
  DailyMonthDTO,
  DailyYearDTO,
  DeleteCategoryResult,
  FeedConfigDTO,
  HistoryIndexDTO,
  InformResultDTO,
  SaveCategoryRequest,
  SaveSourceRequest,
  ScheduleDTO,
  SecretsViewDTO,
  SourceDTO,
  SourceQueryRequest,
} from '../bindings/github.com/vogo/informer/cmd/informer-ui/models'
