import MarkdownIt from 'markdown-it'
import DOMPurify from 'dompurify'

// A daily report is generated by informer, but it is still a file on disk that a
// user - or anything with write access to the data directory - may have edited, and
// the desktop webview runs it with the privileges of the app. So the renderer is
// locked down twice: markdown-it never passes raw html through, and the result is
// sanitised before it reaches the dom.
const renderer = new MarkdownIt({
  html: false,
  linkify: true,
  breaks: true
})

// links open in the system browser through the wails runtime, never inside the
// webview, so a report can never navigate the app away from itself.
renderer.renderer.rules.link_open = (tokens, idx, options, _env, self) => {
  const token = tokens[idx]
  const href = token.attrGet('href') ?? ''

  token.attrSet('href', href)
  token.attrSet('target', '_blank')
  token.attrSet('rel', 'noopener noreferrer')

  return self.renderToken(tokens, idx, options)
}

// renderMarkdown turns one daily report into html that is safe to inject.
export function renderMarkdown(source: string): string {
  return DOMPurify.sanitize(renderer.render(source), {
    ALLOWED_URI_REGEXP: /^(?:https?|mailto):/i,
    FORBID_TAGS: ['style', 'form', 'input', 'iframe', 'object', 'embed'],
    FORBID_ATTR: ['style', 'onerror', 'onload']
  })
}
